apiVersion: v1
kind: Pod
metadata:
  generateName: openshift-shell-1-
  labels:
    app: openshift-shell
spec:
  containers:
    -
      name: openshift-shell
      image: 'quay.io/alpha_weepee_io/openshift-shell:latest'
      ports:
      resources:
        limits:
          cpu: 150m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 50Mi
      terminationMessagePath: /dev/termination-log
      imagePullPolicy: Always
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
